// coverage:ignore-file

import 'package:dhakaniya_gam/app/app.dart';
import 'package:get/get.dart';

part 'app_routes.dart';

/// Contains the list of pages or routes taken across the whole application.
/// This will prevent us in using context for navigation. And also providing
/// the blocs required in the next named routes.
///
/// [pages] : will contain all the pages in the application as a route
/// and will be used in the material app.
/// Will be ignored for test since all are static values and would not change.
class AppPages {
  static var transitionDuration = const Duration(milliseconds: 300);

  static const initial = _Paths.introThreeScreen;
  static final pages = <GetPage>[
    GetPage<SplashScreen>(
      name: _Paths.splashScreen,
      transitionDuration: transitionDuration,
      page: SplashScreen.new,
      binding: SplashBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<IntroFirstScreen>(
      name: _Paths.introFirstScreen,
      transitionDuration: transitionDuration,
      page: IntroFirstScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<IntroSecondScreen>(
      name: _Paths.introSecondScreen,
      transitionDuration: transitionDuration,
      page: IntroSecondScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<IntroThreeScreen>(
      name: _Paths.introThreeScreen,
      transitionDuration: transitionDuration,
      page: IntroThreeScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<LoginScreen>(
      name: _Paths.LoginScreen,
      transitionDuration: transitionDuration,
      page: LoginScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<RegisterScreen>(
      name: _Paths.registerScreen,
      transitionDuration: transitionDuration,
      page: RegisterScreen.new,
      binding: RegisterBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<HomeScreen>(
      name: _Paths.homeScreen,
      transitionDuration: transitionDuration,
      page: HomeScreen.new,
      binding: HomeBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ParivarikVigatScreen>(
      name: _Paths.parivarikVigatScreen,
      transitionDuration: transitionDuration,
      page: ParivarikVigatScreen.new,
      binding: ParivarikVigatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ParivarSabhayVigatScreen>(
      name: _Paths.parivarSabhayVigatScreen,
      transitionDuration: transitionDuration,
      page: ParivarSabhayVigatScreen.new,
      binding: ParivarSabhayVigatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ParivarSabhayVigatListScreen>(
      name: _Paths.parivarSabhayVigatListScreen,
      transitionDuration: transitionDuration,
      page: ParivarSabhayVigatListScreen.new,
      binding: ParivarSabhayVigatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VideshSabhayVigatListScreen>(
      name: _Paths.videshSabhayVigatListScreen,
      transitionDuration: transitionDuration,
      page: VideshSabhayVigatListScreen.new,
      binding: VideshSabhayVigatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VideshSabhayVigatScreen>(
      name: _Paths.videshSabhayVigatScreen,
      transitionDuration: transitionDuration,
      page: VideshSabhayVigatScreen.new,
      binding: VideshSabhayVigatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<OtherDetailsScreen>(
      name: _Paths.otherDetailsScreen,
      transitionDuration: transitionDuration,
      page: OtherDetailsScreen.new,
      binding: ParivarikVigatBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SelectLanguageScreen>(
      name: _Paths.selectLanguageScreen,
      transitionDuration: transitionDuration,
      page: SelectLanguageScreen.new,
      binding: SelectLanguageBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<DashboardScreen>(
      name: _Paths.dashboardScreen,
      transitionDuration: transitionDuration,
      page: DashboardScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SabhayYadiScreen>(
      name: _Paths.sabhayYadiScreen,
      transitionDuration: transitionDuration,
      page: SabhayYadiScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SalahakarSamitiScreen>(
      name: _Paths.salahakarSamitiScreen,
      transitionDuration: transitionDuration,
      page: SalahakarSamitiScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<TalukaRepresentativeScreen>(
      name: _Paths.talukaRepresentativeScreen,
      transitionDuration: transitionDuration,
      page: TalukaRepresentativeScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VillageRepresentativScreen>(
      name: _Paths.villageRepresentativScreen,
      transitionDuration: transitionDuration,
      page: VillageRepresentativScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<DonorsListScreen>(
      name: _Paths.donorsScreen,
      transitionDuration: transitionDuration,
      page: DonorsListScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<DonorsDetailsScreen>(
      name: _Paths.donorsDetails,
      transitionDuration: transitionDuration,
      page: DonorsDetailsScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<UploadResultListScreen>(
      name: _Paths.uploadResultListScreen,
      transitionDuration: transitionDuration,
      page: UploadResultListScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<UploadResultScreen>(
      name: _Paths.uploadResultScreen,
      transitionDuration: transitionDuration,
      page: UploadResultScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<QualifyPrizeListScreen>(
      name: _Paths.qualifyPrizeListScreen,
      transitionDuration: transitionDuration,
      page: QualifyPrizeListScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<QualifyPrizeScreen>(
      name: _Paths.qualifyPrizeScreen,
      transitionDuration: transitionDuration,
      page: QualifyPrizeScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<QualifyStationeryListScreen>(
      name: _Paths.qualifyStationeryListScreen,
      transitionDuration: transitionDuration,
      page: QualifyStationeryListScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<QualifyStationeryScreen>(
      name: _Paths.qualifyStationeryScreen,
      transitionDuration: transitionDuration,
      page: QualifyStationeryScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<OtpScreen>(
      name: _Paths.otpScreen,
      transitionDuration: transitionDuration,
      page: OtpScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BottomBarScreen>(
      name: _Paths.bottomBarScreen,
      transitionDuration: transitionDuration,
      page: BottomBarScreen.new,
      binding: BottomBarBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<NotificationScreen>(
      name: _Paths.notificationScreen,
      transitionDuration: transitionDuration,
      page: NotificationScreen.new,
      binding: NotificationBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ProfileScreen>(
      name: _Paths.profileScreen,
      transitionDuration: transitionDuration,
      page: ProfileScreen.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SabhyFeeRasid>(
      name: _Paths.sabhyFeeRasidScreen,
      transitionDuration: transitionDuration,
      page: SabhyFeeRasid.new,
      binding: ProfileBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SevaoScreen>(
      name: _Paths.sevaoScreen,
      transitionDuration: transitionDuration,
      page: SevaoScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SekshanikSahayYojnaScreen>(
      name: _Paths.sekshanikSahayYojnaScreen,
      transitionDuration: transitionDuration,
      page: SekshanikSahayYojnaScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SabhayYadiDeatilsScreen>(
      name: _Paths.sabhayYadiDeatilsScreen,
      transitionDuration: transitionDuration,
      page: SabhayYadiDeatilsScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VerifyIdentityScreen>(
      name: _Paths.verifyIdentityScreen,
      transitionDuration: transitionDuration,
      page: VerifyIdentityScreen.new,
      binding: AuthBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddAbhyasKartiDikri>(
      name: _Paths.addabhyaskartiDikriScreen,
      transitionDuration: transitionDuration,
      page: AddAbhyasKartiDikri.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BhalamanKarnarScreen>(
      name: _Paths.bhalamanKarnarScreen,
      transitionDuration: transitionDuration,
      page: BhalamanKarnarScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ValiNiBankDetailScreen>(
      name: _Paths.valiniBankDetailScreen,
      transitionDuration: transitionDuration,
      page: ValiNiBankDetailScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VidhvaSahayYojna>(
      name: _Paths.vidhvaSahayYojnaScreen,
      transitionDuration: transitionDuration,
      page: VidhvaSahayYojna.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VidhvaBenNiVigatScreen>(
      name: _Paths.vidhvaBennivigatScreen,
      transitionDuration: transitionDuration,
      page: VidhvaBenNiVigatScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<BalkoNiVigatScreen>(
      name: _Paths.balkoNiVigatScreen,
      transitionDuration: transitionDuration,
      page: BalkoNiVigatScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddBalkoScreen>(
      name: _Paths.addBalkoScreen,
      transitionDuration: transitionDuration,
      page: AddBalkoScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VagerVyajeLoanScreen>(
      name: _Paths.vagerVyajLoanYojnaScreen,
      transitionDuration: transitionDuration,
      page: VagerVyajeLoanScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VidhyarthiniAbhyasNiVigat>(
      name: _Paths.vidhyarthiniAbhyasVigatScreen,
      transitionDuration: transitionDuration,
      page: VidhyarthiniAbhyasNiVigat.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddLoanNiVigatAddScreen>(
      name: _Paths.loanniVigatScreen,
      transitionDuration: transitionDuration,
      page: AddLoanNiVigatAddScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VidhyarthiniAbhyasNiVigat>(
      name: _Paths.vidhyarthiniAbhyasniVigatScreen,
      transitionDuration: transitionDuration,
      page: VidhyarthiniAbhyasNiVigat.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AbhyasKramNiVigatScreen>(
      name: _Paths.abhyasKramNiVigatScreen,
      transitionDuration: transitionDuration,
      page: AbhyasKramNiVigatScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<KharchNiVigatScreen>(
      name: _Paths.kharchNiVigatScreen,
      transitionDuration: transitionDuration,
      page: KharchNiVigatScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<KutumbKamataSabhyListScreen>(
      name: _Paths.kutumbMaKamataSabhyoScreen,
      transitionDuration: transitionDuration,
      page: KutumbKamataSabhyListScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddKamataSabhyScreen>(
      name: _Paths.addKamataSabhyScreen,
      transitionDuration: transitionDuration,
      page: AddKamataSabhyScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddKamataSabhyScreen>(
      name: _Paths.addKamataSabhyScreen,
      transitionDuration: transitionDuration,
      page: AddKamataSabhyScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<HodedarScreen>(
      name: _Paths.hodedarScreen,
      transitionDuration: transitionDuration,
      page: HodedarScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<YuvaSayojakScreen>(
      name: _Paths.yuvaSayojakScreen,
      transitionDuration: transitionDuration,
      page: YuvaSayojakScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<SevaKiyParvutiScreen>(
      name: _Paths.sevaKiyParvutiScreen,
      transitionDuration: transitionDuration,
      page: SevaKiyParvutiScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VidhavaOtherDetailsScreen>(
      name: _Paths.vidhavaOtherDetailsScreen,
      transitionDuration: transitionDuration,
      page: VidhavaOtherDetailsScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<PresidentScreen>(
      name: _Paths.presidentScreen,
      transitionDuration: transitionDuration,
      page: PresidentScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<AddKhetiVigatScreen>(
      name: _Paths.addKhetiVigatScreen,
      transitionDuration: transitionDuration,
      page: AddKhetiVigatScreen.new,
      binding: SevaoBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GalleryScreen>(
      name: _Paths.galleryScreen,
      transitionDuration: transitionDuration,
      page: GalleryScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<ShowFullScareenImage>(
      name: _Paths.showFullScareenImage,
      transitionDuration: transitionDuration,
      page: ShowFullScareenImage.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VillageYadiListScreen>(
      name: _Paths.villageYadiListScreen,
      transitionDuration: transitionDuration,
      page: VillageYadiListScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<VillageYadiDetailScreen>(
      name: _Paths.villageYadiDetailScreen,
      transitionDuration: transitionDuration,
      page: VillageYadiDetailScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<GalleryDetailsScreen>(
      name: _Paths.galleryDetailsScreen,
      transitionDuration: transitionDuration,
      page: GalleryDetailsScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
    GetPage<NotificationDetailsScreen>(
      name: _Paths.notificationDetailsScreen,
      transitionDuration: transitionDuration,
      page: NotificationDetailsScreen.new,
      binding: DashboardBinding(),
      transition: Transition.fadeIn,
    ),
  ];
}
