// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK3om1Cq-Gd0BNKs0xNas-RML-s0c9twQ',
    appId: '1:1005307780330:web:cc59025366c0b02fb2cb93',
    messagingSenderId: '1005307780330',
    projectId: 'dhakaniya-c03ec',
    authDomain: 'dhakaniya-c03ec.firebaseapp.com',
    storageBucket: 'dhakaniya-c03ec.firebasestorage.app',
    measurementId: 'G-1HKVPSZT2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXUUv09s8FH2piU5L6vPcWF9PJ-L_jxW8',
    appId: '1:1005307780330:android:702c424d1b716fccb2cb93',
    messagingSenderId: '1005307780330',
    projectId: 'dhakaniya-c03ec',
    storageBucket: 'dhakaniya-c03ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc8KeaO4i0tUJc97i9a_tplMdFZtXmz_0',
    appId: '1:1005307780330:ios:52223d3faa2ff401b2cb93',
    messagingSenderId: '1005307780330',
    projectId: 'dhakaniya-c03ec',
    storageBucket: 'dhakaniya-c03ec.firebasestorage.app',
    iosBundleId: 'com.dhandhuka.dhandhukataluka.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc8KeaO4i0tUJc97i9a_tplMdFZtXmz_0',
    appId: '1:1005307780330:ios:37e9f3cff44c2ca9b2cb93',
    messagingSenderId: '1005307780330',
    projectId: 'dhakaniya-c03ec',
    storageBucket: 'dhakaniya-c03ec.firebasestorage.app',
    iosBundleId: 'com.dhandhuka.dhandhukaTaluka',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK3om1Cq-Gd0BNKs0xNas-RML-s0c9twQ',
    appId: '1:1005307780330:web:25d7b1bb6281b416b2cb93',
    messagingSenderId: '1005307780330',
    projectId: 'dhakaniya-c03ec',
    authDomain: 'dhakaniya-c03ec.firebaseapp.com',
    storageBucket: 'dhakaniya-c03ec.firebasestorage.app',
    measurementId: 'G-JVRJEFYW3V',
  );
}
